// config.js
window.EMAILJS_PUBLIC_KEY = "${NEXT_PUBLIC_EMAILJS_PUBLIC_KEY}";
window.EMAILJS_SERVICE_ID = "${NEXT_PUBLIC_EMAILJS_SERVICE_ID}";
window.EMAILJS_TEMPLATE_ID = "${NEXT_PUBLIC_EMAILJS_TEMPLATE_ID}";
